/*
 *****************************************************************************
 * Automatically Generated tcp.h
 * ----------------------------------
 * This file was automatically generated by the `generate_module.py` script
 * on 2025-03-03 17:26:37.
 *
 * It defines core TCP structures required for the test framework.
 * Note: This file does NOT include congestion control structures (e.g., bictcp, bbr).
 *
 * ⚠ WARNING: If you modify this file manually, be aware that rerunning
 * the `generate_module.py` script will overwrite any changes.
 * ✅ To customize the generated content, consider modifying `generate_module.py`.
 *****************************************************************************
*/

#ifndef TCP_H
#define TCP_H

#include <stdint.h>
#include "cc_helper_function.h"

#define TCP_INIT_CWND 10
#define TCP_INFINITE_SSTHRESH   0x7fffffff

struct tcp_sock {
    u64 snd_ssthresh;
    u64 tcp_mstamp;
    u64 snd_cwnd;
    u64 snd_nxt;
};

struct sock {
    u64 sk_pacing_rate;
    struct tcp_sock tcp_sock;
    u64 sk_pacing_status;
    struct bictcp *bictcp;
};

#define tcp_sk(sk) (&(sk->tcp_sock))
#define inet_csk_ca(sk) ((sk->bictcp))

#endif /* TCP_H */
