/*
 *****************************************************************************
 * Automatically Generated /home/maryam/FreeBSD/test_dir/cc.h
 * ----------------------------------
 * This file was automatically generated by the `generate_module.py` script
 * on 2025-05-01 14:41:48.
 *
 * It defines core CC structures required for the test framework.
 * Note: This file does NOT include congestion control structures.
 *
 * ⚠ WARNING: If you modify this file manually, be aware that rerunning
 * the `generate_module.py` script will overwrite any changes.
 * ✅ To customize the generated content, consider modifying `generate_module.py`.
 *****************************************************************************
*/

#ifndef CC_H
#define CC_H
#include <stdint.h>
#include <sys/time.h>

struct cc_var {
    void *cc_data;
    uint64_t bytes_this_ack;
    struct { struct tcpcb *tcp; } ccvc;
};

struct tcpcb {
    uint64_t t_srtt;
    uint64_t snd_ssthresh;
    uint64_t snd_cwnd;
    uint64_t t_maxseg;
};

#define CCV(ccv, field) ((ccv)->ccvc.tcp->field)

#endif /* CC_H */
