/*
 *****************************************************************************
 * Automatically Generated /home/maryam/SEARCH/SEARCH_TEST_FRAMEWORK/test_framework/framework/test_dir/tcp.h
 * ----------------------------------
 * This file was automatically generated by the `generate_module.py` script
 * on 2025-03-06 15:44:44.
 *
 * It defines core TCP structures required for the test framework.
 * Note: This file does NOT include congestion control structures (e.g., bictcp, bbr).
 *
 * ⚠ WARNING: If you modify this file manually, be aware that rerunning
 * the `generate_module.py` script will overwrite any changes.
 * ✅ To customize the generated content, consider modifying `generate_module.py`.
 *****************************************************************************
*/

#ifndef TCP_H
#define TCP_H

#include <stdint.h>
#include "cc_helper_function.h"

#define TCP_INIT_CWND 10
#define TCP_INFINITE_SSTHRESH   0x7fffffff

struct tcp_sock {
    u64 mss_cache;
    u64 snd_cwnd;
    u64 bytes_acked;
    u64 tcp_mstamp;
    u64 snd_ssthresh;
};

struct sock {
    struct tcp_sock tcp_sock;
    struct bictcp *bictcp;
};

#define inet_csk_ca(sk) ((sk->bictcp))
#define tcp_sk(sk) (&(sk->tcp_sock))

#endif /* TCP_H */
